### PR TITLE
TruckLoadingDemo: Replace jcenter with mavencentral & add .gitignore …

### PR DESCRIPTION
**Pull request by nilac8991**

### CODE REVIEW

**Comment by nilac8991** [comment]
@nrcg87  @knxp34  Could we please review and merge this? Thanks.

**Comment by knxp34** [comment]
I don't have any knowledge of this repo so I can't comment. However I noticed that your CodeQL checks are failing.....

**Comment by nilac8991** [comment]
@knxp34 I've mentioned you because you were author of the recent commit so I thought you had access.
The CI code implemented in this repo is useless, it's uncompleted and it doesn't reflect the builds steps to compile the Android Projects present in this repo, that's why it's failing for any change that's being made...

**Comment by nilac8991** [comment]
Hi @knxp34 so you want me to remove the entire yaml file?
I can't create labels since I am not a maintainer of the repository....

**Comment by nrcg87** [comment]
I can take care of creating the label.


From: Calin Daniel Neamtu ***@***.***>
Reply-To: ZebraDevs/DataWedge-Android-Samples ***@***.***>
Date: Tuesday, September 13, 2022 at 4:02 AM
To: ZebraDevs/DataWedge-Android-Samples ***@***.***>
Cc: "Wei, Catherine" ***@***.***>, Mention ***@***.***>
Subject: Re: [ZebraDevs/DataWedge-Android-Samples] TruckLoadingDemo: Replace jcenter with mavencentral & add .gitignore … (PR #6)

[External Email]

Hi @knxp34<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knxp34&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=jI1nAKcUZyDp-tXy6t5hisnN8czChosElX6Cnbyir6O596FKk_d2p6uGgiQmQJD0&s=AsZ8jbEw2NUdup3Ixqeo7XmaPGhnTN0hOZU3gEWQDas&e=> so you want me to remove the entire yaml file?
I can't create labels since I am not a maintainer of the repository....

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZebraDevs_DataWedge-2DAndroid-2DSamples_pull_6-23issuecomment-2D1245044142&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=jI1nAKcUZyDp-tXy6t5hisnN8czChosElX6Cnbyir6O596FKk_d2p6uGgiQmQJD0&s=noFCXWVNHmw8ax9pTtCd0AfX2o5vdWZwjbQyX8pgalg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJS7HJ65OHK2XXMJNBRBUELV6AYHPANCNFSM6AAAAAAQIVZJDM&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=jI1nAKcUZyDp-tXy6t5hisnN8czChosElX6Cnbyir6O596FKk_d2p6uGgiQmQJD0&s=HfVQnD1b9n8YD8eja70SvSpAv0Z_K2tBG-DMSY4Q9Yg&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


________________________________
- CONFIDENTIAL-

This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.

**Comment by nilac8991** [comment]
@nrcg87 Could you please tell me why we have a CI script in the repository that essentially doesn't do anything because it's not written to build Android Projects? Also, thanks for the label but only the maintainers can assign labels to Pull Requests....

**Comment by nrcg87** [comment]
Can you let me know where the CI script is?


From: Calin Daniel Neamtu ***@***.***>
Reply-To: ZebraDevs/DataWedge-Android-Samples ***@***.***>
Date: Wednesday, September 14, 2022 at 2:49 AM
To: ZebraDevs/DataWedge-Android-Samples ***@***.***>
Cc: "Wei, Catherine" ***@***.***>, Mention ***@***.***>
Subject: Re: [ZebraDevs/DataWedge-Android-Samples] TruckLoadingDemo: Replace jcenter with mavencentral & add .gitignore … (PR #6)

[External Email]

@nrcg87<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nrcg87&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=oCXFJ8StFjIrgycFA2ujWg7DGtDqADPELRcmlxtjy84U-FO_mAk4cYXEAlr-GU7u&s=CPrjcjyra6RjCVA4F4BCdRDUDJAdnexEyIWxfervJqY&e=> Could you please tell me why we have a CI script in the repository that essentially doesn't do anything because it's not written to build Android Projects? Also, thanks for the label but only the maintainers can assign labels to Pull Requests....

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ZebraDevs_DataWedge-2DAndroid-2DSamples_pull_6-23issuecomment-2D1246321167&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=oCXFJ8StFjIrgycFA2ujWg7DGtDqADPELRcmlxtjy84U-FO_mAk4cYXEAlr-GU7u&s=9NpBB1aKoHoJC4wsVlRPotUgiMMMR2q9VeBJoRxpCSs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJS7HJZHUHMHQ4N47CBKKVDV6FYQDANCNFSM6AAAAAAQIVZJDM&d=DwMCaQ&c=Qwsh1H-X9ypOoLLEcAIltRyC0Dw0FG3Mmyd56ahml5w&r=sTB9_Nxzgj-D1WpiH5an3rzJl5gJtddin9o_qwDBROI&m=oCXFJ8StFjIrgycFA2ujWg7DGtDqADPELRcmlxtjy84U-FO_mAk4cYXEAlr-GU7u&s=JaRz0lPzmi5lGl8VU79Vch3r4HH9Z0PrLLs4OqB3HfE&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


________________________________
- CONFIDENTIAL-

This email and any files transmitted with it are confidential, and may also be legally privileged. If you are not the intended recipient, you may not review, use, copy, or distribute this message. If you receive this email in error, please notify the sender immediately by reply email and then delete this email.

**Comment by nilac8991** [comment]
https://github.com/ZebraDevs/DataWedge-Android-Samples/blob/master/.github/workflows/codeql-analysis.yml
And, if you check the 62 line, it tries to compile bootstrap, probably as a dependency which has absolutely nothing to do with the repository

**Comment by knxp34** [comment]
If you don’t want to have failed CodeQL actions then yes you should remove the yaml file.

**Comment by knxp34** [comment]
Hi

You don't need to update labels just Follow the ReadMe requirements located here: https://confluence.zebra.com/display/EETP2/GitHub+Repository+Requirements

Thanks
-Tom

**Comment by nilac8991** [comment]
@knxp34 this PR was closed weeks ago, please check my merged commits for the changes.

**Pull request closed without merging**
